packages:
  - "apps/*"
  - "packages/*"
overrides:
  "react": "19.1.1"
  "react-dom": "19.1.1"
  "@types/react": "19.1.1"
  "@types/react-dom": "19.1.1"
  "react-test-renderer": "19.1.1"
  "react-native": "0.82.1"